// LOGIN CONSTANT
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

//REGISTER CONSTANT
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

//LOGOUT CONSTANT
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

//LOAD USER
export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

//ALL USERS
export const ALL_USER_REQUEST = "ALL_USER_REQUEST";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_REQUEST";

// //DELETE MESSAGES
// export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
// export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
// export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";
// export const DELETE_MESSAGE_RESET = "DELETE_MESSAGE_RESET";

//CLEAR ERRORS
export const CLEAR_ERRORS = "CLEAR_ERRORS";
