import React from "react";
import Head from "next/head";
import Link from "next/link";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Index = () => {
  return (
    <div>
      <div>
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </Head>
      </div>
      <div className="flex flex-col justify-center items-center h-[80vh]">
        <div className="">Welcome to Video Call website</div>
        <div className="mt-4 text-green-800">
          <Link href="/video">Start Video call</Link>
        </div>
      </div>
    </div>
  );
};

export default Index;
